<?php

namespace BackendBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getClassCode($oportunity, $student)
    {
        $classCode = "ERROR404";

        $credits = $oportunity->getCredits(); //agregar al modelo de datos
        switch ($oportunity->getResponsibleMentor()) {
            case 1:
                $mentorIng = $oportunity->getMainMentor()->getUc();        
                break;

            case 2:
                $mentorIng = $oportunity->getSecondaryMentor()->getUc();        
                break;

            case 3:
                $mentorIng = $oportunity->getThertiaryMentor()->getUc();        
                break;
            
            default:
                $mentorIng = false;
                break;
        }
        
        $studentIng = $student->getUC();
        $cmd = $oportunity->getCmd();
        $time = 1;///falta la itegracion con siding 746e
        $graded = $oportunity->getModality();

        //get classcode object
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM BackendBundle:ClassCode c
                WHERE c.mentorIng = :mentorIng
                AND c.credits = :credits
                AND c.studentIng = :studentIng
                AND c.cmd = :cmd
                AND c.time = :time
                AND c.graded = :graded'
            )->setParameters(array('mentorIng' => $mentorIng, 'credits' => $credits, 'studentIng' => $studentIng, 'cmd' => $cmd, 'time' => $time, 'graded' => $graded));
     
        try 
        {
            $classCodeObject = $query->getResult();
            $classCodeObject = $classCodeObject[0];
        }
        catch (\Doctrine\ORM\NoResultException $e) 
        { 
            return "ERROR404";
        }

        //si su code es XXXX usamos el del depto
        $initials = $classCodeObject->getInitialsCode();
        if($initials = "XXXX")
            $initials = $oportunity->getDepartment();
        else
            $initials = $classCodeObject->getInitialsCode();

        //retornamos la concatenacion de la sigla y el numero
        return array('initialsCode' => $initials, 'numbersCode' => $classCodeObject->getNumbersCode());
    }

	public function findByStudentId($id)
	{
        $returnResults = null;

	    $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM BackendBundle:Application a
                JOIN a.student s
                WHERE s.id = :id'
            )->setParameter('id', $id);
     
        try {
            $mainResults = $query->getResult();

            if (count($mainResults) > 0 )
                $returnResults = $mainResults;
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        return $returnResults;
	}

    public function findOneByStudentIdAndOportunityId($studentId, $oportunityId)
    {
        $returnResults = null;

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM BackendBundle:Application a
                JOIN a.student s
                JOIN a.oportunityResearch o
                WHERE s.id = :ids
                AND o.id = :ido'
            )->setParameters(array('ids' => $studentId,'ido' => $oportunityId));
     
        try {
            $mainResults = $query->getResult();

            if (count($mainResults) > 0 )
                $returnResults = $mainResults;
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        return $returnResults[0];
    }

    public function itExists($studentId, $oportunityId)
    {
        $exists = false;

        $results = $this->findOneByStudentIdAndOportunityId($studentId, $oportunityId);

        if (count($results) > 0 )
                $exists = true;

        return $exists;
    }

	public function findByMentorId($id)
	{
        $returnResults = null;

	    $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM BackendBundle:Application a
                JOIN a.oportunityResearch o
                JOIN o.mainMentor mm
                WHERE mm.id = :id'
            )->setParameter('id', $id);
     
        try {
            $mainResults = $query->getResult();

            if (count($mainResults) > 0 )
                $returnResults = $mainResults;
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM BackendBundle:Application a
                JOIN a.oportunityResearch o
                JOIN o.secondaryMentor sm
                WHERE sm.id = :id'
            )->setParameter('id', $id);
     
        try {
            $secondaryResults = $query->getResult();

            if (count($secondaryResults) > 0 )
                if(is_null($returnResults))
                    $returnResults = $secondaryResults;
                else
                    $returnResults = array_merge($returnResults,$secondaryResults);
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM BackendBundle:Application a
                JOIN a.oportunityResearch o
                JOIN o.thertiaryMentor tm
                WHERE tm.id = :id'
            )->setParameter('id', $id);
     
        try {
            $thertiaryResults = $query->getResult();

            if (count($thertiaryResults) > 0 )
                if(is_null($returnResults))
                    $returnResults = $thertiaryResults;
                else
                    $returnResults = array_merge($returnResults,$thertiaryResults);
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        return $returnResults;
	}
}
