<?php

namespace BackendBundle\Repository;

/**
 * ClassCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
