<?php

namespace BackendBundle\Repository;

/**
 * DeadlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeadlineRepository extends \Doctrine\ORM\EntityRepository
{
}
