<?php

namespace BackendBundle\Repository;

/**
 * EmailListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailListRepository extends \Doctrine\ORM\EntityRepository
{
}
