<?php

namespace BackendBundle\Repository;

/**
 * KeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordsRepository extends \Doctrine\ORM\EntityRepository
{
}
