<?php

namespace BackendBundle\Repository;

/**
 * OportunityResearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OportunityResearchRepository extends \Doctrine\ORM\EntityRepository
{
}
