<?php

namespace BackendBundle\Repository;

/**
 * OtherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherRepository extends \Doctrine\ORM\EntityRepository
{
}
