<?php

namespace BackendBundle\Repository;

/**
 * RestorerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestorerRepository extends \Doctrine\ORM\EntityRepository
{
}
