<?php

namespace BackendBundle\Repository;

/**
 * TimeLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
