<?php

namespace BackendBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNextSyntheticRut()
    {
    	$nextSyntheticRut = 1;

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u.rut FROM BackendBundle:User u'
            );
     
        try {
            $ruts = $query->getResult();

        } catch (\Doctrine\ORM\NoResultException $e) {
            $ruts = null;
        }

        if(count($ruts) > 0 )
        {
        	for ($i = 1; $i <= count($ruts); $i++) 
        	{
        		$nextSyntheticRut = $i;
			    if($i < $ruts[$i])
			    	break;
			}
        }

        return $nextSyntheticRut;
    }

    public function getAdminsMailArray()
    {
        $returnResults = null;

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM BackendBundle:User u
                WHERE u.role like \'%ROLE_ADMIN%\'');
     
        try 
        {
            $admins = $query->getResult();

            $returnResults = array();

            foreach ($admins as $user) 
            {
                $returnResults[$user->getEmail()] = $user->getShowName();
            }
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            
        }

        return $returnResults;
    }
}
