services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  backend.form.type.oportunityResearch:
    class: BackendBundle\Form\Type\OportunityResearchType
    arguments: [ "@doctrine.orm.entity_manager" ]