backend_time_limit:
    resource: "@BackendBundle/Controller/TimeLimitController.php"
    type:     annotation

backend_email_list:
    resource: "@BackendBundle/Controller/EmailListController.php"
    type:     annotation

backend_deadline:
    resource: "@BackendBundle/Controller/DeadlineController.php"
    type:     annotation

backend_prerequisite:
    resource: "@BackendBundle/Controller/PrerequisiteController.php"
    type:     annotation

backend_user:
    resource: "@BackendBundle/Controller/UserController.php"
    type:     annotation

backend_research:
    resource: "@BackendBundle/Controller/ResearchController.php"
    type:     annotation

backend_requirement:
    resource: "@BackendBundle/Controller/RequirementController.php"
    type:     annotation

backend_oportunity_research:
    resource: "@BackendBundle/Controller/OportunityResearchController.php"
    type:     annotation

backend_notification:
    resource: "@BackendBundle/Controller/NotificationController.php"
    type:     annotation

backend_keyword:
    resource: "@BackendBundle/Controller/KeywordController.php"
    type:     annotation

backend_department:
    resource: "@BackendBundle/Controller/DepartmentController.php"
    type:     annotation

backend_application:
    resource: "@BackendBundle/Controller/ApplicationController.php"
    type:     annotation

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path:   /logout

backend_security:
    resource: "@BackendBundle/Controller/SecurityController.php"
    type:     annotation

backend_misc:
    resource: "@BackendBundle/Controller/MiscController.php"
    type:   annotation

backend_faculty:
    resource: "@BackendBundle/Controller/FacultyController.php"
    type:   annotation

backend_class_code:
    resource: "@BackendBundle/Controller/ClassCodeController.php"
    type:   annotation

backend_reporter:
    resource: "@BackendBundle/Controller/ReporterController.php"
    type:   annotation

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /