security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            logout:
                invalidate_session: true
                path:   /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login_check

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_MENTOR]

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/application/$, roles: [ROLE_MENTOR, ROLE_STUDENT] }
        - { path: ^/application/[0-9]+$, roles: [ROLE_MENTOR, ROLE_STUDENT] }
        - { path: ^/application/new, roles: ROLE_STUDENT }
        - { path: ^/application/[0-9]+/edit$,, roles: ROLE_ADMIN }

        - { path: ^/notification/$, roles: [ROLE_STUDENT, ROLE_MENTOR, ROLE_OTHER] }
        - { path: ^/notification/[0-9]+$, roles: [ROLE_MENTOR, ROLE_STUDENT, ROLE_OTHER] }
        - { path: ^/notification/new$, roles: [ROLE_MENTOR, ROLE_STUDENT, ROLE_OTHER] }
        - { path: ^/notification/[0-9]+/edit$, roles: ROLE_ADMIN }

        - { path: ^/keyword/$, roles: [ROLE_MENTOR, ROLE_STUDENT, ROLE_OTHER] }
        - { path: ^/keyword/[0-9]+, roles: [ROLE_MENTOR, ROLE_STUDENT, ROLE_OTHER] }
        - { path: ^/keyword/new$, roles: ROLE_MENTOR }
        - { path: ^/keyword/[0-9]+/edit$, roles: ROLE_ADMIN }

        - { path: ^/oportunityresearch/$, roles: [ROLE_STUDENT, ROLE_MENTOR,ROLE_OTHER] }
        - { path: ^/oportunityresearch/[0-9]+$, roles: [ROLE_STUDENT, ROLE_MENTOR,ROLE_OTHER] }
        - { path: ^/oportunityresearch/new, roles: ROLE_MENTOR }
        - { path: ^/oportunityresearch/[0-9]+/edit$, roles: ROLE_MENTOR }

        - { path: ^/department/$, roles: [ROLE_MENTOR, ROLE_STUDENT] }
        - { path: ^/department/[0-9]+$, roles: [ROLE_MENTOR, ROLE_STUDENT] }
        - { path: ^/department/new$, roles: ROLE_ADMIN }
        - { path: ^/department/[0-9]+/edit$, roles: ROLE_ADMIN }

        - { path: ^/requirement, roles: ROLE_MENTOR }

        - { path: ^/research/$, roles: [ROLE_MENTOR, ROLE_STUDENT] }
        - { path: ^/research/[0-9]+$, roles: ROLE_ADMIN }
        - { path: ^/research/new$, roles: ROLE_ADMIN }
        - { path: ^/research/[0-9]+/edit$, roles: ROLE_ADMIN }

        - { path: ^/user/$, roles: ROLE_ADMIN }
        - { path: ^/research/[0-9]+$, roles: [ROLE_STUDENT, ROLE_MENTOR,ROLE_OTHER] }
        - { path: ^/research/[0-9]+/edit$, roles: [ROLE_STUDENT, ROLE_MENTOR,ROLE_OTHER] }
    providers:
        in_memory:
            memory:
                users:
                    alumno:  { password: alumnopass, roles: 'ROLE_STUDENT' }
                    mentor:  { password: mentorpass, roles: 'ROLE_MENTOR' }
                    otro:  { password: otropass, roles: 'ROLE_OTHER' }
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext