security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            logout:
                invalidate_session: true
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_MENTOR]

    access_control:
        - { path: ^/application, roles: ROLE_STUDENT }
        - { path: ^/application, roles: ROLE_STUDENT }
        - { path: ^/keyword, roles: ROLE_MENTOR }
        - { path: ^/oportunityresearch, roles: [ROLE_STUDENT, ROLE_MENTOR] }
        - { path: ^/oportunityresearch/new, roles: ROLE_MENTOR }
        - { path: ^/department, roles: ROLE_ADMIN }
        - { path: ^/requirement, roles: ROLE_MENTOR }
        - { path: ^/research, roles: [ROLE_MENTOR,ROLE_ADMIN, ROLE_STUDENT] }
        - { path: ^/research/new, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        # Descomenta la siguiente línea para proteger también
        # la propia URL /admin
        # - { path: ^/application$, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    alumno:  { password: alumnopass, roles: 'ROLE_STUDENT' }
                    mentor:  { password: mentorpass, roles: 'ROLE_MENTOR' }
                    otro:  { password: otropass, roles: 'ROLE_OTHER' }
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext